apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: admin
  name: admin

spec:
  selector:
    matchLabels:
      app: admin

  template:
    metadata:
      labels:
        app: admin

    spec:
      containers:
        - image: ghcr.io/quaternionmedia/al-admin:main
          imagePullPolicy: Always
          name: admin
          envFrom:
            - configMapRef:
                name: admin-config
            - secretRef:
                name: admin-secret
