apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credentials
spec:
  storageClassName: vultr-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
