apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: alfred
  name: alfred

spec:
  selector:
    matchLabels:
      app: alfred

  template:
    metadata:
      labels:
        app: alfred

    spec:
      containers:
        - image: ghcr.io/quaternionmedia/alfred:main
          imagePullPolicy: Always
          name: alfred
          command:
            ['uvicorn', 'alfred.main:app', '--host', '0.0.0.0', '--port', '80']
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
